[project]
name = "05-text-news-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.44.1",
    "torch>=2.6.0",
    "transformers>=4.51.1",
]
